---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "training-operator.serviceAccountName" . }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "training-operator.fullname" . }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kubeflow.org
    resources:
      - tfjobs
      - tfjobs/status
      - tfjobs/finalizers
      - pytorchjobs
      - pytorchjobs/status
      - pytorchjobs/finalizers
      - mxjobs
      - mxjobs/status
      - mxjobs/finalizers
      - xgboostjobs
      - xgboostjobs/status
      - xgboostjobs/finalizers
      - mpijobs
      - mpijobs/status
      - mpijobs/finalizers
      - paddlejobs
      - paddlejobs/status
      - paddlejobs/finalizers
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - '*'
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - '*'
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "training-operator.fullname" . }}
  labels:
    {{- include "training-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "training-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "training-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}