apiVersion: v1
kind: ServiceAccount
metadata:
  name: training-operator
  labels:
    app: training-operator
  {{- include "training-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.trainingOperator.serviceAccount.annotations | nindent 4 }}