apiVersion: v1
kind: Service
metadata:
  name: training-operator
  labels:
    app: training-operator
  {{- include "training-operator.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.trainingOperator.type }}
  selector:
    control-plane: kubeflow-training-operator
  {{- include "training-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.trainingOperator.ports | toYaml | nindent 2 }}