apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference.fullname" . }}
  labels: {{- include "inference.labels" . | nindent 4 }}
spec:
  ports:
    {{- range $key, $value := .Values.ingress }}
    {{- if hasPrefix "path" $key }}
    {{- with $value }}
    {{- $index := $key | trimPrefix "path" }}
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http{{ $index }}
    {{- end }}
    {{- end }}
    {{- end }}
  selector: {{- include "inference.selectorLabels" . | nindent 4 }}
