apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference.fullname" . }}
  labels: {{- include "inference.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ingress.path.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ingress.path1 }}
    - port: {{ .Values.ingress.path1.port }}
      targetPort: http1
      protocol: TCP
      name: http1
    {{- end }}
  selector: {{- include "inference.selectorLabels" . | nindent 4 }}
