apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference.fullname" . }}
  labels: {{- include "inference.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ingress.path.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "inference.selectorLabels" . | nindent 4 }}
