apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpi-operator
  labels:
    app: mpi-operator
    app.kubernetes.io/component: mpijob
    kustomize.component: mpi-operator
  {{- include "mpi-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.mpiOperator.serviceAccount.annotations | nindent 4 }}