apiVersion: v2
name: training-operator  # 这行是必需的
description: A Helm chart combining MPI Operator and Training Operator
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mpi-operator-chart
    version: "0.1.0"
    repository: "file://charts/mpi-operator-chart"
  - name: training-operator-chart
    version: "0.1.0"
    repository: "file://charts/training-operator-chart"
