{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: vc-addl-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
spec:
    policyTypes:
    - Egress
    podSelector: 
        matchLabels:
            vcluster.loft.sh/managed-by: {{ .Release.Name }}
    egress:
    # Allows outgoing connections to the external http proxy
    - to:
        - ipBlock:
            cidr: 10.255.128.100/27
      ports:
      - protocol: TCP
        port: 3128
    # Allows outgoing connections to the internal nginx ingress
    - ports:
      - port: 443
        protocol: TCP
      to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
{{- end }}