{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pod.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostName := include "ingress.host" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pod.labels" . | nindent 4 }}
  annotations:
    {{- include "ingress.annotations" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ $hostName | quote }}
      {{- if .Values.ingress.secretName }}
      secretName: {{ .Values.ingress.secretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
