apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod.fullname" . }}
  labels:
    {{- include "pod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pod.selectorLabels" . | nindent 4 }}

---

{{- if .Values.service.sshPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pod.fullname" . }}-ssh
  labels:
    {{- include "pod.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    {{- include "pod.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.sshPort }}
      targetPort: 22
{{- end }}
