{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Release.Name }}-limit-range
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
spec:
  limits:
  - default:
      {{- range $key, $val := .Values.limitRange.default }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    defaultRequest:
      {{- range $key, $val := .Values.limitRange.defaultRequest }}
      {{ $key }}: {{ $val | quote }}
      {{- end }}
    type: Container
{{- end }}