{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-workloads
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  {{- if .Values.globalLabels }}
  labels:
  {{ toYaml .Values.globalLabels | indent 4 }}
  {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
spec:
  podSelector: {}
  egress:
    # Allows outgoing connections to DNS server
    - ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    # Allows outgoing connections to the internet or
    # other vcluster workloads
    - to:
        - namespaceSelector: 
            matchLabels:
                name: {{ .Values.namespace | default .Release.Namespace }}
        - ipBlock:
            cidr: {{ .Values.networkPolicy.outgoingConnections.ipBlock.cidr }}
            except:
              {{- range .Values.networkPolicy.outgoingConnections.ipBlock.except }}
              - {{ . }}
              {{- end }}
    {{- with .Values.networkPolicy.outgoingConnections.egress }}
    {{ . | toYaml | nindent 4 }}
    {{- end }}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-control-plane
  namespace: {{ .Release.Namespace }}
  {{- if .Values.globalLabels }}
  labels:
  {{ toYaml .Values.globalLabels | indent 4 }}
  {{- end }}
  {{- if .Values.globalAnnotations }}
  annotations:
{{ toYaml .Values.globalAnnotations | indent 4 }}
  {{- end }}
spec:
  podSelector: {}
  egress:
    # Allows outgoing connections to all pods with
    # port 443, 8443 or 6443. This is needed for host Kubernetes
    # access
    - ports:
        - port: 443
        - port: 8443
        - port: 6443
    # Allows outgoing connections to all vcluster workloads
    # or kube system dns server
    - to:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: 'kube-system'
          podSelector:
            matchLabels:
              k8s-app: kube-dns
  policyTypes:
    - Egress
{{- end }}